### ISSUE TITLE
(Manual Alignment Tool) shifts are displayed as zero after a state is loaded

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1186]
When a state file is loaded for an aligned dataset (manual alignment has been run), the shifts appear as zero despite having non-zero values (i.e. the dataset remains aligned).

**Comment by mathturtle** [comment]
I made a state with some large shifts with manual image alignment so that it should be obvious if the shifts are applied or not.  When I load the state file back in, for an instant I see the original data until the pipeline runs and the shifts are applied.  Then it updates and I see the data with the shifts applied.  I opened the edit window for the manual align widget and it had the shifts I expected.  So is this fixed or did I do something wrong in my testing of it?

**Comment by cryos** [comment]
We should look into moving the table to the active image that is being displayed, it can be confusing that you move through the image stack but the table remains at the top, can we manipulate the active row/column in response to changing the active slice in the UI?

**Comment by mathturtle** [comment]
I think this can be closed now.

**Comment by cryos** [comment]
Yes, it looks good to me. Please reopen if you still see issues @Hovden.
