### ISSUE TITLE
Save load state can run operations twice

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1236]
There is a problem with the "Load output from Save Data rather than the original" behavior. If you ran operations before saving the data, it treats the file as if it were the original and runs those operations on it again...

Load dataset.
Square root
Save Data
Save State
Reset/close & reopen tomviz
Load State --> data will have been square rooted twice.

**Comment by cryos** [comment]
I am not sure if this is a real bug, it is exactly what I would expect as you changed the starting point by saving over the original data. We have been thinking about making the data source simpler, such that it only contains one vtkImageData, not two as it does now. I think this will naturally lead to a more intuitive API, and a clearer pipeline.

Right now we have:
- DataSource (original + transformed)
-- Operators
-- Visualization modules

If we move to:
- DataSource (original)
-- Operators
-- DataSource2 (transformed)
-- Visualization modules

You will not be surprised in the least that saving over the original with the transformed would lead to it being transformed again. It is the implicit duality which then has to be flattened when you save that makes things confusing in my opinion. Unless this is not what you mean, in which case perhaps some ASCII art pipelines would explain it better to me.

**Comment by mathturtle** [comment]
Mostly the issue is that I didn't save over the original data file.  It was still there (and so I would argue the state file should have opened that one).  I saved a new file beside it, but tomviz prefers loading the 'Save Data' output to loading the original file.

**Comment by cryos** [comment]
It is largely because we are conflating two things in our pipeline though - the original and the transformed data. If I save the data, I expect to save the output, but if I save the state I expect to be able to re-run the pipeline. If these two elements were separated then we could preserve the filename of the input data, and update the filename of the saved data.

Having something that is implicitly both makes things confusing. How could we save the input data to a different filename/format in the current interface, and have that be reloaded next time as we prefer using EMD for all of our data for example. Another we have been thinking about is:
![image](https://user-images.githubusercontent.com/42214/29137176-66687570-7d0d-11e7-9579-4bfd2ae16689.png)
that is visually difficult to process, the reconstruction child data set is explicit, and what the volume render is rendering. The Outline and Orthogonal Slice modules are confusing, what are they rendering? It is the implicit transformed data that is not represented in the pipeline.

**Comment by Hovden** [comment]
We noticed that the pipeline runs twice from a state file once you have "reset" the software. Loading a state runs all pipeline steps equal to the number of times you have "reset". A fresh reboot (closing and reopening) of the software doesn't cause this.

**Comment by ercius** [comment]
Yes. That is how this happened the first time. I was running through a lot
of tests that day.

**Comment by cryos** [comment]
I hadn't seen that, we can create an issue for the reset bug.

**Comment by mathturtle** [comment]
Is anyone looking at this reset bug yet?

**Comment by cjh1** [comment]
Its all yours :smile:

**Comment by mathturtle** [comment]
So the only case where I can reproduce the double pipeline runs is if I do a "Save Data" and the already processed data gets loaded rather than the original.  Every other case with "Reset" has only run the pipeline once (although I did find some other bugs, see #1244, #1246, and #1247).

**Comment by cryos** [comment]
@cjh1 this is the issue I was thinking of, let's create a new issue to track this, reference this as it has some discussion, but use that going forward.

**Comment by cryos** [comment]
I think this was largely resolved in 1.2.0, the tracking of the separation will occur in #1322.
