### ISSUE TITLE
Animation movie export issues

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1285]
Exporting a camera orbit as an AVI produces a stuttering movie. The reason is that the frame rate is set to 1 fps by default. Can this be changed to a more useful value? It should probably be something like 30 fps.

Also, it seems that the AVI is written without compression. I compressed a short movie from ~1GB to 512k  in VLC. Can we add compression or is it already compressed?

**Comment by mathturtle** [comment]
Changing the default frame rate is easy (I'll push a branch in a minute).

The AVI encoding format actually depends on the "Quality" slider in the dialog.  Its value is put into this expression `static_cast<int>(3 * quality / 100.0)` and the result determines the compression level.  If the resulting level is `>= 2`, then compression is disabled.  At lower levels it uses some form of compression that becomes more lossy the lower the resulting integer  (I'm not sure about the details, I haven't looked any further down than the vtkFFMPEGWriter's documentation).  Also, if you are unfamiliar with C++, `static_cast<int>` behaves like the mathematical `floor` function for positive numbers.  I'm not sure why we need a slider from 0 to 100 when the result is put into a function that expects an integer from 0 to 2 either...

**Comment by ercius** [comment]
Frame rate change is great. This is buried in the "advanced settings" dialog which most users will not find. Maybe we should expose this better?

Can we set the quality to some value that will use some compression? Most users do not need huge video files. The 0-100 slider is pretty useless is the value is floored. Using your info and equation I see that the file size is not affected by the slider for large ranges.

Setting the quality value to <63.333 kicks in the compression and file size is 1/100 original size using MJPG codec. A value of 10 gets another 1/3 reduction. I see a little quality reduction with a value of 10. Maybe a radio button is better?

Further, its difficult to choose the size other than the default. Is there a way to add a "preview" of 1 image which will show the field of view of the final image?

**Comment by mathturtle** [comment]
I can certainly make a custom version of this dialog for tomviz and expose different options.  The frame rate being and advanced option seems strange to me.  We could make it visible by default and also do something about the quality slider.

I can certainly change the default quality value so that we use some compression.  I was very surprised when I realized we had a 0 to 100 slider for something that has 3 values.  It really should be a drop down or radio button, but I think it has more detailed control if you are saving out to a series of images.  This control should probably change based on the format the user has selected.  @utkarshayachit Thoughts?

ParaView just recently added a "Preview Mode" that shows what the image would look like if you saved it out at a given size.  We can probably enable that in tomviz.

**Comment by utkarshayachit** [comment]
> 0 to 100 slider for something that has 3 values

Since the interpretation of compression depends on the file format chosen and the file name is selected after the options are specified, it was done as a percentage, but I am open to other ideas. Just make sure that things are consistent when saving animations and screenshot.

> ParaView just recently added a "Preview Mode"

Preview mode is still being refined (see [this](https://gitlab.kitware.com/paraview/paraview/merge_requests/1889)). I'd suggest waiting for that to happen.
