### ISSUE TITLE
Separate out "original" and "transformed" data sources

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1322]
#1236

**Comment by cjh1** [comment]
Here is an example of the current progress:

![pipe](https://user-images.githubusercontent.com/1031053/32345342-428491c8-bfe0-11e7-88f7-9af7642cbd2a.png)

I don't think the "[Transformed]" postfix works ...

**Comment by cryos** [comment]
No, but it does summarize what I was describing well, and is described as transformed in the current data source dialog.

**Comment by cjh1** [comment]
Here is another example, closer to the situation we were discussing with @Hovden in the meeting yesterday:

![example](https://user-images.githubusercontent.com/1031053/32391946-36831d70-c0aa-11e7-96ad-087a918b4d47.png)

**Comment by cryos** [comment]
I intend to merge #1364 soon as this branch is already quite large, and spans quite some time. I think the general direction is good, and am happy to have sorted out many of the issues with the running pipeline. Major issues that need to be tracked here (and possibly broken out into a few follow up issues with trackers) are:

- [ ] Ensure serialization/deserialization fully support data sources, operators, and modules in the updated pipeline, supporting restoring saved copies of child data/reconstructions, etc
- [ ] Logic in the pipeline for removing operators, and keeping the "output" in the right place
- [ ] Default to appending operators to linear chain rather than creating more branches
- [ ] Develop appropriate pipeline execution animation to show pipeline as it runs
- [ ] Locate default modules such that they show pipeline output data

Serialization/deserialization needs to be rewritten, I have been experimenting with JSON, and in light of significant changes to the DataSource, which I think set us up well for the advanced pipeline we need, I am not sure there is value in porting the existing code. I started developing on this branch, but think serialization/deserialization would be better completed in a follow up branch. I see some good paths, but could use input on the pipeline, operators, ensuring we keep track of child data sets.

**Comment by cjh1** [comment]
#1378
