### ISSUE TITLE
Cannot launch tomviz on Windows 7

### ISSUE THREAD

**Issue by AbhiGHub** [OpenChemistry/tomviz#1359]
I have tried to launch versions 1.2.1 as well as 1.2.0. I tried it on 2 different machines, both running Windows 7.
Here is a message in Event Log:
(ERROR)
Faulting application name: tomviz.exe, version: 0.0.0.0, time stamp: 0x59ea7628
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x4804c
Faulting application start time: 0x01d36a087a2ea5c9
Faulting application path: C:\Program Files\tomviz\bin\tomviz.exe
Faulting module path: unknown
Report Id: c1a97979-d5fb-11e7-bb79-002590e6afeb

Fault bucket 52986011, type 503889069
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: tomviz.exe
P2: 0.0.0.0
P3: 59ea7628
P4: StackHash_1dc2
P5: 0.0.0.0
P6: 00000000
P7: 0000000000000000
P8: c0000005
P9: 0000000000000008
P10: 

Attached files:
C:\Users\agunde\AppData\Local\Temp\WERB929.tmp.WERInternalMetadata.xml
C:\Users\agunde\AppData\Local\Temp\WERC442.tmp.appcompat.txt

These files may be available here:
C:\Users\agunde\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_tomviz.exe_3b80c98db2f8ffbfea54bae4e352f5a0c3f823f7_8f25c4fc

Analysis symbol: 
Rechecking for solution: 0
Report Id: c1a97979-d5fb-11e7-bb79-002590e6afeb
Report Status: 1

**Comment by mathturtle** [comment]
The machine I tested on here was Windows 7, so this is likely something to do with the machine itself.  Are you accessing it remotely via remote desktop? (if so see #1192, there are some issues in Windows itself).  Otherwise, what graphics hardware are you using?  Typically a crash on startup indicates that something with the system is incompatible with tomviz, and it is usually the graphics card.

**Comment by AbhiGHub** [comment]
Hi mathturtle,
I didn't use remote desktop. Where can find the requirements for graphics card? Thanks!

**Comment by cryos** [comment]
Sorry, it looks like you never got a response on this. The minimum version of OpenGL requires is OpenGL 3.3, we do try to have Tomviz report when requirements are not met, but there are times when it crashes on startup while probing for the necessary capabilities. You might try updating the graphics card drivers, we have tested Intel, ATI and NVIDIA cards which should all work but it may need a driver update in order to get OpenGL 3.3+ working.

**Comment by cryos** [comment]
Closing due to lack of response, we have minimum OpenGL requirements that look like the likely cause of this issue.
