### ISSUE TITLE
View Menu broken

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#136]
[Tested on Linux] 
View menu is not accessible, instead it reports an error:

[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Axes Toolbar" under id 47 
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Camera Toolbar" under id 48 
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "VCR Toolbar" under id 49 
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Visualization Modules Toolbar" under id 50

**Comment by mathturtle** [comment]
This is a know issue with Qt 4 on Ubuntu 14.04.  Apparently Ubuntu's new unity menu system restricts menu items from being in two places in the menus and the menu items only show up in the first place that they are registered (which in this case is NOT in the View menu, so the View menu is empty).

Switching to Qt 5 may fix this (I haven't had a chance to test it yet), but I've known about this for a while since it affects ParaView too.

@utkarshayachit Remember this one?

**Comment by utkarshayachit** [comment]
Yes Qt/Core/pqOutputWindow.cxx is supposed to detect these and eat them up. @mathturtle Can you check if some of the recent updates to pqOutputWindow broke this, by any chance? Thanks.

**Comment by mathturtle** [comment]
I'm not aware that it **ever** ate those events.  At least not on my system.  I'll have a look.

**Comment by mathturtle** [comment]
@Hovden If you put the focus back on tomviz without closing the error dialog, you can access the view menu (without the offending menu items).  The dialog appearing is what cancels the menu access.

**Comment by Hovden** [comment]
@mathturtle good to know. Thanks. I can move forward with some work.

**Comment by mathturtle** [comment]
I've put together a ParaView merge request to suppress these errors (actually warnings, which is why they weren't getting suppressed before).

https://gitlab.kitware.com/paraview/paraview/merge_requests/252

**Comment by Hovden** [comment]
View menu warnings no longer appear in my newest Ubuntu build.
