### ISSUE TITLE
Drawing issue on high DPI screens

### ISSUE THREAD

**Issue by hdevyldere** [OpenChemistry/tomviz#1385]
Using Windows 10 on a 3840 x 2160 resolution screen the File, Data Transforms, Segmentation, etc. buttons are not visible (Fig. 1). 
![2018-01-11](https://user-images.githubusercontent.com/35352799/34854137-aa52014e-f6ec-11e7-98f2-ade559068ef6.png)
The drop down menus for each are still accessible by clicking slightly below where each button should be (Figure 2). 
![screenshot 1](https://user-images.githubusercontent.com/35352799/34854141-b0988a64-f6ec-11e7-8d30-5cc2daee261d.png)
To click highlight and use any of the visible buttons on the GUI you must hover and click slightly below them (Figure 3).
![screenshot 3](https://user-images.githubusercontent.com/35352799/34854198-0a9ec17c-f6ed-11e7-89ec-e47eb1776936.png)

I've tried changing the screen resolution and changing the compatibility- no combination of those have fixed the issue.

**Comment by cquammen** [comment]
Thank you for the bug report. I am guessing that your system is defaulting to use an Intel chipset for rendering. Unfortunately, there is an Intel driver bug that is likely responsible. See the discussion thread on the ParaView issue tracker (tomviz is built on ParaView) (here)[https://gitlab.kitware.com/paraview/paraview/issues/17499] and an Intel bug (here)[https://communities.intel.com/thread/116003].

You can either update your Intel graphics driver to see if that resolves the issue. If you have another discrete graphics card on your computer, you will see improved performance if you switch tomviz to use that for rendering. If you have an NVIDIA graphics card, this can be done in the NVIDIA configuration panel. Add a configuration for the tomviz executable and choose to use the NVIDIA High performance processor instead of the global default. Run tomviz and you should see the menu bar again.

Please let us know one way or another if you are able to resolve the problem with these solutions.

**Comment by hdevyldere** [comment]
Thank you for getting back to me so quickly. Switching to the NVIDIA
graphics card like you suggested, solved the problem! The steps you gave
were really helpful too.


Thank you again,

Hannah D.

**Comment by cquammen** [comment]
Fantastic, thanks for confirming it worked for you.

**Comment by ercius** [comment]
In case someone finds this again, I was able to fix this issue on my Windows 10 Dell XPS 13 9343. I updated the BIOS from A15 released in February 2018 downloaded directly from Dell. So, it was not a Intel graphics card issue, but a bios issue. Or somehow interrelated. This fixed QT issues in both tomviz and Spyder (the Python IDE).
