### ISSUE TITLE
Multiple transform dialogs can be open at once

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1422]
It is currently possible to open an arbitrary number of some transform dialogs from the menus at a time (e.g. I can just keep clicking "Set Tilt Angles" or "Mark Data as Tilt Series" over and over again and more dialog boxes pop up).  This can be confusing for the user, so maybe we should prevent that.

I notice that some transform dialogs (like "Rotate") grey out all menu items while they are open to prevent more dialogs from being opened or transforms from being run.  Maybe whatever those ones do should be implemented consistently.

**Comment by mathturtle** [comment]
Notes:  python operator dialogs were modal in the last released version (which I believe is what Elliot is using).  Since then these dialogs have changed to be non-modal (so they no longer grey out the menus).  If we want to change them back to being modal we can, but we should discuss this (and probably make all the operator dialogs consistent).  I seem to remember changing other dialogs to not be modal...

**Comment by cryos** [comment]
Rob specifically wanted to avoid modal dialogs for operators so that you could interact with data, click apply, etc without locking the applicaiton. I think our handling of dialogs could be improved - the set tilt angles, mark data as tilt series etc should be modal in my opinion, but we should also look at keeping a pointer to an opened dialog in the class that opens it and calling show, rather than creating a new dialog each time and setting it to delete on close.

We can certainly take a look at improving consistency in the dialogs, but there are good reasons to avoid making all dialogs modal. When they are not modal we need to work on ensuring you only get one dialog for any particular thing, you shouldn't be able to have three dialogs for the same operator, we did some work for the Python operators and taking a quick look they do not spawn multiple dialogs but that may have been changed after the last stable release.

**Comment by mathturtle** [comment]
> you shouldn't be able to have three dialogs for the same operator

That is correct, there should only be one dialog per operator.  This issue is when you are creating new operators Data Transforms->Rotate pops up a dialog with no operator associated with it (since the operator isn't added to the pipeline until you hit apply).  Then you are free to use the menu item Data Transforms->Rotate again and it will create a new dialog.  Accepting both dialogs creates two operators.

The change from the last release is that the dialogs created from the Data Transforms and other menus used to be modal and now are not so you can have multiple "new operator" dialogs.

**Comment by cryos** [comment]
I think the work @alesgenova is doing will improve this, we will disable adding new operators until you have finished with the new one just added. We can link this to the pull request once it is ready, but I think we keep the non-modal dialogs but only allow adding one operator at a time.
