### ISSUE TITLE
Tomography Menu Not Accessible: Mark Data as Tilt Series

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1450]
Mark data as a tilt series does not allow processes from the tomography menu to be run.

<img width="987" alt="screen shot 2018-03-22 at 1 15 53 pm" src="https://user-images.githubusercontent.com/6197997/37786816-f5460a38-2dd3-11e8-9807-083ab5974782.png">

**Comment by cjh1** [comment]
@Hovden It looks to me like you have deleted the "Output" data source created by the "Set Tilt Angles" operator? That is the data source that would have the tomography menu enabled for ( as it has the tilt  angles ). So I think the problem here is more that you where able to delete the "Output" data source, we should probably not allow that.

**Comment by mathturtle** [comment]
@cjh1 I think that is a good point: we should prevent the Output from being deleted.

But consider this:  If I have the Set Tilt Angles selected and add a square root to the pipeline it goes on the end.  But with that same selection I can't add a Image Alignment operator even though it would be legal to put it on the end (as the output is a tilt series).  This is inconsistent.

**Comment by cjh1** [comment]
@mathturtle I will push a PR to prevent deletion, I agree the use case you detail should also be fixed up.

**Comment by cjh1** [comment]
Related #1454

**Comment by cjh1** [comment]
Related #1453

**Comment by cjh1** [comment]
Yep!
