### ISSUE TITLE
Trivial Producer and other animator issues

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#154]
There are a few sub-issues here, (labeled 1 through 4) but all relate to the animator.

1) Animation that causes instant crash
When you load up a reconstruction and you want to create an animation, there are a number of camera options. 
One is called "Trivial Producer 1" (see below)
![trivial producer](https://cloud.githubusercontent.com/assets/12704237/9209048/97d7d10a-4042-11e5-8b44-7cd8e73047e5.PNG)
When you hit the + button to add the animation, Tomviz just closes/crashes, and you lose everything you've been working on. This is not good. 

2) Animation that needs a tweak
![camera follow path](https://cloud.githubusercontent.com/assets/12704237/9210522/c3c69d34-404a-11e5-9594-2b285eda950b.PNG)
I really like the animations you can do with Camera -> Follow Path, but the camera positions you start out with after selecting follow path need to be improved for user friendliness. Initially, all the pre-programmed camera positions cluster in a tight circle about the origin (see below).
![camera positions follow path](https://cloud.githubusercontent.com/assets/12704237/9210541/e9a78a4a-404a-11e5-8ea6-d9ee9aad3622.PNG)
It would be much easier for users to find the camera positions and manipulate the path if the initial camera positions defined a line across one face of the dataset (e.g. below). ![new camera positions follow path](https://cloud.githubusercontent.com/assets/12704237/9210243/273e12f4-4049-11e5-9145-06f032ea37b3.PNG)
I did this with two points for ease of presentation.  Users might want to start with 5 or 6 points to manipulate, but either way, I think a line is the way to go rather than just a large ring, otherwise the follow path and orbit animations would be too similar. 
Another issue with this alignment is that initially, the camera focal position for the follow path animation is set to x = 0, y = 0, z = 0. It needs to be set to the central point of the dataset, otherwise you only get a movie of one small corner of the reconstruction. Users won't want to have to change this every time they make an animation. 

3) Animation that doesn't seem to work
There is also a "Camera -> Follow Data" Option, but I can never get that to do anything. Does it do anything? 
![camera follow data](https://cloud.githubusercontent.com/assets/12704237/9210547/f3994926-404a-11e5-8527-d998e848ff83.PNG)

4) Suggested new animation 
A useful option that we don't seem to have yet is an animation for the orthoslice and non-orthoslice modes where it runs through all the slices in a stack / reconstruction sequentially (like at 0.50 in the tomviz demo video http://www.tomviz.org/, except this would be an animation rather than a manual screen recording). This will be especially useful for users looking to create an animation to show off internal features of their sample (like pore structure).

**Comment by mathturtle** [comment]
I'll take a look at 1) for now.  The others will require some discussion, but I can fix the crash.

**Comment by mathturtle** [comment]
Ok, this is messy.  Essentially, we have a proxy for the vtkTrivialProducer that shouldn't have any properties listed as animatable since it has no representation.  In fact it shouldn't even appear in this list.  I put together a patch to check the assertion that is failing and avoid the index out of bounds that is occurring, but then adding an animation to the trivial producer defaults to adding a python animation.  Huh?  Why does the trivial producer show up in the list if it does nothing?

@utkarshayachit I'd appreciate your input on fixing this crash.  The assertion that is failing is the QList out of bounds check (trying to get item 0 from an empty list) at pqAnimatablePropertiesComboBox.cxx line 296.  But the real problem is that the trivial producer shows up as an option at all.

**Comment by mathturtle** [comment]
I patched ParaView so that it won't crash.  Superbuild PR is [here](https://github.com/OpenChemistry/tomviz-superbuild/pull/51).  It still doesn't do the right thing when you have the vtkTrivialProducer selected but it doesn't crash.  Other animation panel issues will wait until we redesign the animation panel to be tomviz-specific rather than just reusing ParaView's.

**Comment by Hovden** [comment]
If it doesn't crash, we can close this issue and revisit animation down the road.
