### ISSUE TITLE
Runing Tomviz on RHEL (Linux) fails - missing shared objects/CXXABI

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1587]
I want to use tomviz on a linux system (redhat v7.5).
After unzip the binary file, how should I do to start the program?
I try to run './bin/tomviz' but get errors like "./tomviz: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./tomviz)"

**Comment by cryos** [comment]
I think your Linux version is too old for the Docker image we are compiling on. This is Red Hat Enterprise Linux 7.5 I assume? I am surprised as we are using a Debian release I think.

**Comment by yijiang1** [comment]
Yes I'm using Red Hat Enterprise v7.5. So I guess my solution is to use a Debian-based linux system.

**Comment by cryos** [comment]
I had hoped it would work there, we can look at whether we can make our binaries more compatible - I had hoped it would work on RHEL 7.5, it may actually be that it would but we need to include the C++ standard library in our package. Leave it with me a little while, this could just be something we missed in packaging.

**Comment by mathturtle** [comment]
The docker image we use for our linux binaries is Debian 8-based.  This is probably newer than RHEL 7.5 :(  We could adjust the image to be based on some other distro, the issue is getting compilers that support enough C++11 on an older distro.

ParaView has done a lot of work to get their superbuild to work on CentOS 6 since I made this decision (Linux was/is not our priority so moving forward to debian 8 was simpler than figuring out porting to CentOS).  We may be able to port to an image similar to pvbinsdash without much trouble now (but I don't know since ParaView still only needs VS2013-ish C++11 and we need more).
