### ISSUE TITLE
Double clicking on histogram produces contour

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1595]
If you double click on the histogram then a contour is created with its value set to where you double click. I think this functionality is not necessary and cumbersome for some users. In some cases the user double clicks on the histogram by accident and then the computer freezes for some time while calculating the contour. 

I suggest removing this functionality or at least providing a pop-up dialog with the prefilled value and ok/cancel to create a contour.

**Comment by cryos** [comment]
I think there is value in this, Rob and I worked on it early on. It would probably be good to confirm at least the first time they want to do this, with a possibility of suppressing it in future clicks.

**Comment by cjh1** [comment]
@psavery Can add a confirmation dialog for the double click event? I think that and the other improvements you have made should resolve this issue.

**Comment by ercius** [comment]
I think that is a good idea. It at least makes it clear to the user what
happened.

**Comment by psavery** [comment]
Will do.

**Comment by psavery** [comment]
How does something like this look?

![im3](https://user-images.githubusercontent.com/9558430/43160715-f8515002-8f53-11e8-8350-d1eb8b2ab471.png)

When the user double-clicks on the histogram, this dialog would appear instead of the one in PR #1618. The double slider widget is only enabled if "Create contour?" is checked.

If the user checks 'Don't ask again', it will from now on do one of the following:
1. If "Create contour?" was checked: always create a contour when the user double-clicks the histogram.
2. If "Create contour?" was not checked: never create a contour when the user double-clicks the histogram.

If the user clicks the "x", the contour is not created and no settings are saved.

**Comment by ercius** [comment]
I suggest changing this in the following ways:
1. Use an Ok/Cancel dialog box. Then the user can easily cancel if it
happened by accident. I see many new users accidentally create contours
this way.
2. Change the title to Create contour
3. Remove the "create contour?" check box. It's unnecessary.
4. Remove the "don't ask again" option. How would the user reenable this if
they wanted the option back? (Otherwise keep it if there is a way to
reenable it)
5. The slider should always be enabled

Lastly, can there be a live preview option check box? Or will that be
prohibitively slow? I think the contour algorithm is faster now.

**Comment by cryos** [comment]
I think we need to offer a don't ask again, I and many others find these dialogs very annoying. Also, I would rather not add a live preview - you can already do that in the panel, duplicating here is not necessary. Agreed on removing the create contour - with ok/cancel it is duplicating things.

**Comment by cjh1** [comment]
I think the "create contour" check box is there to make is clear if a contour should create. To me it would be a little confusing to have the cancelling of the dialog cause a contour not be created in the future?

**Comment by cryos** [comment]
For me this is a confirmation dialog - are you sure you want to create the contour you just asked for? So OK would go ahead and create it, Cancel would cancel the creation of the contour. It is perhaps a nice extra to have the slider, but I am not sure that is necessary - you already chose the value in the histogram, but if we have it for free, then I think it looks nice.

Don't ask again is because we designed the double click to allow quite interactive clicking around in the histogram, and I use that to explore data while looking at the histogram - this dialog is very disruptive when using it in that mode.

**Comment by ercius** [comment]
Its good to hear from others that use this feature. My suggestions were from my own experience of having this feature occur by accident. I do not use it at all mostly because of the speed issue (hopefully solved now).

The Ok/Cancel dialog was to be used as @cryos described. The cancel button should not be used to save the setting. It is a one time cancel. I agree that there should be a way to avoid showing this dialog again. How about if that is only true for the current session? When you restart tomviz it pops up the first time again.

OR

Since the contour creation is very fast then we dont need an Ok/Cancel dialog. However, I still think that there should be some feedback to the user that double clicking on the histogram created the contour. How about we just make a box show up with a title like "Creating contour from double click" and a progress bar? The wording of the title is awkward though.

OR

Do nothing. Leave it as is without a doalog box. If the contour generation is fast then it might not affect users at all. They will figure out that double clicking creates a contour either from tutorials or by accident/exploration.

Im ok with any option. I suggest people who use this regularly (i.e. @cryos ) should be the final vote.

**Comment by cryos** [comment]
Erring on do nothing right now, we can revisit post release.

**Comment by ercius** [comment]
I think this dialog made it into the 1.4.0 tagged version: #1696
