### ISSUE TITLE
Error when running tomviz under 64 bit arch linux.

### ISSUE THREAD

**Issue by 5paceManSpiff** [OpenChemistry/tomviz#162]
After compiling tomviz under 64 bit arch linux it threw the `SIGABORT` signal and exited.  This is the output of the command.

```
ASSERT: "ainfo->GetNumberOfComponents() == 1" in file /home/aaron/test/tomviz/tomviz/Utilities.cxx, line 191
fish: “./bin/tomviz” terminated by signal SIGABRT (Abort)
```

**Comment by mathturtle** [comment]
What does your dataset look like?  Currently tomviz only supports data with single component arrays and this assertion is the check to make sure that the array being processed has only a single component.

@cryos This should probably not be an assert, but a error printout since it can be caused by the user accidentally doing something.  I'll put up a patch to change that.

**Comment by cryos** [comment]
We should tighten up validation of the data, and pop up a warning dialog instead of using an assert. We currently only support volumes with a single component scalar value.

**Comment by 5paceManSpiff** [comment]
@mathturtle Can you link to some example data?  I'm not exactly sure how to import content into tomviz.

**Comment by Hovden** [comment]
Here are some temporarily available datasets for you:
https://drive.google.com/open?id=0B8t3fBhIw9-VMzJaSVE3ZnBwTWc
https://drive.google.com/open?id=0B8t3fBhIw9-VeHo3YktRQkhjSk0

We will have several peer-reviewed datasets publicly available this fall.

**Comment by 5paceManSpiff** [comment]
How is data encoded into a .tiff like that?

**Comment by stevenspurgeon** [comment]
The easiest way to create an image stack .tiff file is to load all the images into ImageJ, then stack them, and export the .tiff.
