### ISSUE TITLE
Extend ability to save and load alignment to automatic alignment operators

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1632]

**Comment by cjh1** [comment]
@yijiang1 Can you fill out a little more detail of your use case?

**Comment by mathturtle** [comment]
Related issue with discussion from a few years ago:
https://github.com/OpenChemistry/tomviz/issues/433

**Comment by yijiang1** [comment]
I want to save and load shifts generated by automatic and manual alignment operators. This allows me to align one dataset and then apply the same set of shifts to another dataset.

One way to do this is to 
1. Add an option for users to output the shifts of automaic alignment operators into a file. 
2. Add a function to read the file and apply the shifts to a tilt series. With #1622, the maual alignment ui can alreay read a json file with integer shifts. It's probably also useful to read and apply sub-pixel shifts? @Hovden To do this we a new python operator and the pipeline and state file should be modified accordingly since the operator is linked to an external file. 

 #433 proposes the idea of integrating the automatic alignment function into the manual alignment ui, which is probably a more elegent design because this way users can see the shifts all the time and don't need to differentiate between the shifts generated by automatic and by manual alignment. 

A bouns feature would be to include tilt axis alignment, which adds two extra outputs: a global shift and a global rotation.
