### ISSUE TITLE
"Delete slices" transform does not save properly in state file

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1643]
binary 1.3.1 on Mac.
tomviz fails to load state files with "delete slices" transform and print this error message:

Failed to parse operator JSON
""

**Comment by mathturtle** [comment]
The issue is that this operator has arguments to its python script but no JSON file to describe them.  Apparently the new state file code doesn't handle that.  There seem to be a few of these.

* Delete Slices
* Clear Subvolume
* Remove Bad Pixels
* Background Subtraction (Manual)

Fixing the deserialization code to ignore the validation of the arguments if there is no JSON fixes some of them, but without the type information all numbers are floats and operators like Delete Slices and Clear Subvolume expect integer indices.  I think the right solution is to provide JSON description files for all of these operators.

**Comment by mathturtle** [comment]
... and I see why this was left the way it was:  The range of the first and last slice fields needs to change with which axis is selected, which is impossible to express in our current operator JSON files.  Let me think about the best way to add it.

**Comment by cryos** [comment]
The JSON is really only used to cast to the correct type when restoring state, maybe we can support that notion, or the restoration code could have an alternative syntax to get expected type information.
