### ISSUE TITLE
Open data won't display in new render view

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#180]
If I open data and set up visualizations for it then open a new render view, the visualization modules cannot be shown in the new render view -- they are associated with just one render view.  I believe this should work as it does in paraview, where any already existing visualization module can be displayed in a new render view.

**Comment by Hovden** [comment]
@ElliotPadgett I think this is a matter of preference.

In fact, I kind of like having two different visualization for the same dataset. For example, one might have a contour visualization on one panel and a volume visualization on the other panel.

**Comment by ElliotPadgett** [comment]
I think you should at least have the option.  The paraview model lets you
choose by letting you set which visualizations are visible in each view.

I also think this model can be more confusing to the user since there is an
implicit association between particular modules and particular views,which
is not shown to the user in any way.  Also, modules can be "orphaned" by
closing their render view, making them appear nowhere.

**Comment by Hovden** [comment]
The ability to choose and also preventing orphaned visualizations would be a good addition.

**Comment by mathturtle** [comment]
After a little digging, this is not a trivial as it sounds.  I agree it is a good idea and should be supported though...

Notes to self: representations have a pointer to the view, so this amounts to having a way to create multiple representations per module (or changing the representation's view pointer).  If we are allowing multiple representations per module so that multiple views can contain the visualization then either they all have to be synced or the properties panel needs updated when the view changes to show the properties of the new representation.

**Comment by cryos** [comment]
I don't think this is something we necessarily want to address, this is the way we designed the visualization modules to work. I am going to close this, but if we want to head in this direction I think we need to revisit some other design decisions.
