### ISSUE TITLE
Tilt axis (manual) uses untransformed data

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1842]
The transformed data during pre-processing (e.g. sqrt, reinterpret signed to unsigned, etc.) is not used in the Tilt Axis (manual) GUI.

1) Load a data set (star tilt series)
2) Apply an obvious transform that modifies the intensities. Sqrt in the default custom transform works.
3) Start the Tilt Axis Alignment (manual)
4) The histogram changes to the old original values. The image on the screen is hard to see (sometimes all black or white) because the colormap is confised as to which data is being shown (see screenshot).
![image](https://user-images.githubusercontent.com/15657108/56311590-4744d400-6103-11e9-8ddd-28073e2143c2.png)

This transform should use the unsigned integers. Im not sure if it's just a display issue or if the transform is also applied to the original data. I think it applies the rotate and shift to the transformed data, but that should be verified.

tomviz 1.6.0, WIndows 10, DEL XPS 13 laptop, intel graphics card.

**Comment by psavery** [comment]
I see that it looks like the histogram also gets reset for some other operators with edit dialogs as well, such as `Image Alignment (Manual)`. I'll take a look at it.

**Comment by psavery** [comment]
@ercius I discussed in #1843 that it appeared that the parent's color map was used instead of the child's color map for the Tilt Axis Alignment (manual) operator. I fixed it there.

I also discussed in that PR that it appears the reason the histogram is changing in the background is just because the parent becomes the active data source (same effect as left clicking on the top row in the pipeline diagram). I don't think it's actually modifying any values, so it might be okay to leave it.

Can you check on a nightly build tomorrow or another day, and confirm that everything is working properly?

**Comment by ercius** [comment]
Thanks for confirming this issue. I'll check it fixed when I get a chance.

**Comment by cryos** [comment]
Is this fixed? It would be good to ensure we have it working in master before our next release.

**Comment by ercius** [comment]
This is working 50%. Only the histogram in the main window is going back to use the original data's values. The GUI uses the transformed  data.

**Comment by psavery** [comment]
As mentioned above, I think the histogram is changing because the active data source is being switched to the parent rather than the child, and this happens for all operators. I can try to see if I can fix it...

**Comment by psavery** [comment]
The PR linked above is a good fix for this, I think. It should fix the rest of the issue.
