### ISSUE TITLE
Viz panels and tabs not loading properly from save State File

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#21]
When saving and loading the tomviz state, the panels and tabs are not restored properly. For example, if one has a tab with three split viz panels and a second tab containing a single viz panel the state will restore with four viz panels in a single tab. 

Also, the size / spacing of the panel splits are not saved.

**Comment by ElliotPadgett** [comment]
@Hovden I'm noticing a related issue: Not all panels keep their configuration when loaded from state files.  For example, if I set up my window by closing the animation panel and hiding the histogram, save state and then load the state file on another machine the animation panel and histogram will be open anyway.

Tomviz seems to be loading the last panel configuration used locally rather than the panel configuration associated with the state file.  (so you will only notice this issue if you change configuration in between saving and loading state.)

Is this the desired behavior?  If not, should we make a separate issue or reopen this?

**Comment by mathturtle** [comment]
@Hovden can answer about desired behavior, but that is that way it currently works.  Which panels are visible is stored on a per-user (I think) basis locally on the machine in the application preferences.

I would argue that it makes sense the way it is: if you send a collaborator a state file, he doesn't want to spend 5 minutes figuring out how you organized your panels, he wants to look at your data in a panel setup that he is familiar with.  Everyone will probably have a slightly different setup based on what makes sense to them.

**Comment by ElliotPadgett** [comment]
I think that picture make sense for experienced users who have used the program before and have preferences about the panel setup.  However, if you wanted to be able to distribute a state file bundled with tomviz for a more general audience (mostly new users) to view you might want to set the panels in a particular way, for example to emphasize the histogram for one data set or the 3D view for another.

I can see both behaviors being useful in some circumstances, so we should think about what we want.
