### ISSUE TITLE
uint16 data in MRC format file imported incorrectly

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#2113]
**Describe the bug**
MRC files with uint16 dtype are incorrectly imported. The file is read in quarters. and the rest of the tilt series is empty. Maybe an issue with the stride when reading?

The screenshot below showing 4 images in one is basically showing the object 1/4 the size at different tilt angles. So, the reader is reducing the size of the image and mixing tilt angles.

Here I read in the original data set which is uint16:
![image](https://user-images.githubusercontent.com/15657108/83546416-7bb95200-a4b5-11ea-84e0-83019da132ca.png)

If  I convert it to int16 or float it loads in like this:
![image](https://user-images.githubusercontent.com/15657108/83546543-af947780-a4b5-11ea-85c8-4f9b3353654a.png)

**To Reproduce**
You can write simple MRC files using ncempy. Here is a script which will output a test data set.

```python
import ncempy.io as nio
import numpy as np
XX, YY, ZZ = np.mgrid[0:10, 0:200, 0:200]
nio.mrc.mrcWriter('uint16.mrc', ZZ.astype(np.uint16), (1,1,1))
nio.mrc.mrcWriter('int16.mrc', ZZ.astype(np.int16), (1,1,1))
```

uint16 (wrong)
![image](https://user-images.githubusercontent.com/15657108/83546938-55e07d00-a4b6-11ea-99a1-76237339b493.png)

int16 (right)
![image](https://user-images.githubusercontent.com/15657108/83546989-67298980-a4b6-11ea-8800-08ed60d89d08.png)

**Expected behavior**
The uint16 should be read in the correct order. It looks like there is some issue with the stride in the MRC reader.

**Screenshots**

**Desktop (please complete the following information):**
 - Window 10
 - tomviz version 1.8.0

**Hardware (please complete the following information):**
 - Device: Surface Book 2
 - Graphics card: on battery...probably Intel

**Additional context**

**Comment by psavery** [comment]
I believe I have located the issue. In the `vtkMRCReader` class, [this should return `1`](https://gitlab.kitware.com/vtk/vtk/-/blob/9674ee42feb7f4325b183b1cbcb70bdb7ba2d5f2/IO/Image/vtkMRCReader.cxx#L208) instead of `2` for mode `6` (modes `3` and `4` should still return `2`).

The [MRC Format Specification](https://bio3d.colorado.edu/imod/doc/mrc_format.txt) indicates that modes `3` and `4` are for complex numbers, and therefore they consist of two components. But mode `6` is `uint16_t`, and should therefore only have one component.

If I make this change, it appears to be correct in Tomviz

![image](https://user-images.githubusercontent.com/9558430/200133313-390a00f7-f94b-4fd5-a681-7b0a576b78da.png)

So I think we will need to make this change in VTK and patch it into Tomviz until we move ParaView forward far enough to contain the change.

**Comment by psavery** [comment]
This is fixed in VTK in [VTK MR !9675](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9675).

**Comment by cjh1** [comment]
I have pushed forward paraview, so we should have the fix in tonight's binary.

**Comment by ercius** [comment]
This is fixed in the 2022-11-15 nightly. Nice!

**Comment by psavery** [comment]
Thanks Peter, I'm closing this one out!
