### ISSUE TITLE
Deleting crop doesn't update visualization

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#217]
Visualizations is not updated when crop is deleted from Data Transforms.

**Comment by Hovden** [comment]
@cryos It looks like cdash is jammed up again? No recent builds for me to test on.

**Comment by cryos** [comment]
I have @mathturtle looking into it, he said they made some major update last week that broke a number of projects (including ours), sorry I wasn't aware of this. It should be fixed, but still seems to be having issues as far as I can tell even when merging the last pull request. We will keep you updated, and should hopefully have everything back to normal soon.

**Comment by mathturtle** [comment]
@Hovden As of late yesterday builds are back on.  The issue was that nothing had been updated since then.  Since we are on Github instead of Kitware's Gitlab, we have to wait for the every 10 minutes 'did something change in tomviz' check for our builds to start.  (The change that broke everything was a way to make builds for projects in Gitlab almost immediate).  Anyway, the latest version is building now.

**Comment by Hovden** [comment]
Works on latest cdash build (OSX)
