### ISSUE TITLE
How to export reconstructed volume? Only not-reconstructed data are exported...

### ISSUE THREAD

**Issue by therob84** [OpenChemistry/tomviz#2292]
I am completely new to TomViz 1.0.0.
I use it for reconstruction of data from a STEM rotating series.
I could manage the reconstruction itself, so I can see in the pipeline the reconstructed "volume", which represents an intensity in x-y-z voxelspace and can see the data in the viewer.

I have now the problem, that I can't manag to export this reconstructed 3D-voxelspace-volume to e.g. TIFF format to further use it in ImageJ or Avizo3D. Always, if I right-click to the "volume" entry in the Tomviz pipeline and choose "export" the resulting TIFF contains still the rotating series (thus the input data), means each TIFF-slice in the stack shows my data still with changing rotation angles - I would expect that each TIFF-slice contains a slice in z-direction of the reconstructed x-y-z-volume. 
Can anybody tell me where I missed the trick for exporting data of my reconstructed volume? Either as single images (in a batch) or as a TIFF containing all z-slices.

Or could this be a bug or a not implemented feature or do I just miss the correct button/work flow?

Thanks for any hints how to manage the export of the reconstructed volume.
Cheers, Robert

**Comment by ercius** [comment]
Hi Robert,

Let me see if I can help you with this. Firstly, are you really use Tomviz 1.0.0? The newest version is Tomviz 1.10 and I highly recommend updating. Also, what type of computer you are using (Mac, Win, Linux)?

I did a quick test with Tomviz 1.10 on a windows 10 machine. I loaded the "star" test tilt series, binned by two (for speed), and then reconstructed with the back projection method. I right clicked on the reconstructed child data set and selected "Save data"

![image](https://github.com/OpenChemistry/tomviz/assets/15657108/6dc4574e-c5a3-47dc-9627-42c47f517c3c)

I saved the data as a TIF as you suggested and loaded it back in Tomviz (and also Fiji). The data that was written to disc was indeed the reconstructed volume. 

Your specific wording indicates that you may be right clicking on a "Volume visualization"  module instead of the child dataset. The screenshot below is what you *dont* want to do:
<img width="218" alt="image" src="https://github.com/OpenChemistry/tomviz/assets/15657108/f0326e0c-04ce-4a86-841d-4734eb6a1f06">

If Im wrong about the "Volume export" hypothesis, it would be good to have answers to the questions above (version and computer type) and a screen shot of your pipeline (with exactly what you clicked on) to further debug this issue.

**Comment by therob84** [comment]
Hello ercius and many thanks for your reply.
Indeed I have to apologize, meanwhile I figured out, that the expected export function - like you confirmed - does work properly, and the problem comes up with my sample data. I gave tomviz a wrong set of tilting angles and the reconstructed result contained of course a lot of artifacts and in consequence the exported volume did show still some "rotating artifacts" which I interpreted as a still rotating volmue by mistak.....  so in short: everything works like expected, and it was my fault. Thanks.
And indeed I use v1.10.

Short other question: can I find any place where I can downlod Tomviz v2.x as windows installer or ZIP-folder (without installation)? In Github I only find the source code, right?

Cheers, Robert

**Comment by ercius** [comment]
The MSI will install over your other stable tomviz v1.10 installation. The ZIP will allow you to have both installed, but you just have to find the .exe (on windows) in the `tomviz/bin` folder to run 2.X.  I have found tomviz 2 quite stable already and the new capabilities/fixes are worth the upgrade. We are looking into finishing version 2 in the near future for general release.

Please let us know if you have any more questions! Good luck with your research.
