### ISSUE TITLE
Deleting a data transform reset tilt angles to zero

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#257]
1. Load a dataset.
2. Mark it as tilt series. Auto fill the tilt angles. 
4. Do python data transform.
5. Delete the transform from the pipeline.
6. Now all tilt angles are reset to zero.

**Comment by mathturtle** [comment]
I see what is happening here.  When the transform is deleted, the code doesn't know if the tilt angles came from the transform (i.e. your convert to tilt series transform) or from the user.  So they are removed.  Then, since the dataset is still marked as a tilt series a new tilt angles array is created with all 0s.

One solution would be to make the 'auto fill tilt angles' into a transform that stores what the user did to the tilt angles...

**Comment by yijiang1** [comment]
> make the 'auto fill tilt angles' into a transform

I think @Hovden does not want this...

**Comment by mathturtle** [comment]
To really address this we need to save where the tilt angles were added/modified in the sequence of transforms applied to a dataset.  The easiest way to do this would be to insert these events as new transforms.  I'll try to think of something else if @Hovden thinks this is a bad idea.
