### ISSUE TITLE
Segmentation Icon Confusing

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#274]
Right now the segmentation icon is confusing. I'm not sure how it works and why it looks like a calculator. We might want to omit this from the next release.

**Comment by mathturtle** [comment]
Right... when I first put in that module I needed an icon and had no idea what it should look like.... so I borrowed the calculator filter icon from ParaView and then forgot to go back and change it later.

**Comment by Hovden** [comment]
Yeah. Also, I don't understand how to use this tool or if it should be treated differently than the other data transforms. Just need to understand the vision and think about it a little.

**Comment by cquammen** [comment]
Is this still an issue? I'm not sure which to which icon this was referring.

**Comment by cquammen** [comment]
Reposing the question. As I work on adding more segmentation features, I still haven't seen the icon in question.

**Comment by mathturtle** [comment]
I don't think this is relevant anymore.  My early attempts to add segmentation as a visualization module used the ParaView calculator icon since I needed a placeholder.  But a) I'm not sure that module exists anymore and b) your segmentation work obsoleted it anyways.  So I think it is safe to close this.

**Comment by cquammen** [comment]
Thanks, Shawn.
