### ISSUE TITLE
Add slider for contour threshold

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#28]
Currently the user must type the values for single isosurface contours.  It would be nice to be able to use a slider for this.  The nicest would be if you could have the threshold shown on top of the histogram (I think Chimera's volume viewer works this way) as well.

**Comment by ElliotPadgett** [comment]
It might be good to add separate modules for "single countour/isosurface" and "contour/isosurface series".  The module as it exists now is great as a "countour/isosurface series" module, but a slider and direct color setting control would be better in a "single contour/isosurface" module.

**Comment by Hovden** [comment]
This was addressed in merge #416 

@mathturtle Great job adding the slider. With the fast contour rendering it is nice and interactive.

I have two minor tweaks before closing:
1) text to the left of slider should read "value" instead of "isosurface"
2) make specular lighting default value non-zero, maybe 0.3?

**Comment by ElliotPadgett** [comment]
Slider works great!  I agree with @Hovden about (1).  The slider label should say "Value".  Is having specular lighting a good default though?

**Comment by ElliotPadgett** [comment]
I think this has been addressed well.  I will open a new issue for the single color selection request.
