### ISSUE TITLE
Manual align wrap around issue

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#302]
I completed a manual alignment on a data set with 62 images. I used the 32nd image as a static reference image for all alignments. I started the alignment at image #33. Upon reaching image #62 I pressed "s" to go to the next image, which "wrapped around" to image 1. I thought, "Great feature. Ill keep aligning now starting at image 1." After finishing the alignment I pressed the align data set.

The transformed data set is only aligned for half of the images which are oddly 1-32. The rest of the images (33-62) are copies of image 32. I think that the desired functionality is to not allow the user to press "s"/"a" to go beyond the maximum/minimum image number.

tomviz 070-16

**Comment by ElliotPadgett** [comment]
I think we wanted it to allow you to continue by "wrapping" when you hit the end of the series.  I think this is a bug with generating the aligned data.

I have also had problems with generating the aligned data where I did a full alignment and then hit the generate button and it just copied the original data with no shifts applied.  Perhaps these are related problems.

**Comment by ElliotPadgett** [comment]
@ercius , Actually I think I understand the problem you're having, and it's not related to the wrapping functionality.  When the manual alignment widget makes the aligned data set it leaves the original one open, so as you scroll through slices in the new one it will at some point go "behind" the original one, so it will look like you are just seeing copies of a particular slice.

Do you think that's what you were seeing?  If so, we can fix this type of confusion by making the manual alignment generate a python transform instead of cloning the data, issue #310.

(I don't know if something similar was happening for me.)

**Comment by ercius** [comment]
Yes...you are right. That's embarrassing. Thanks for pointing this out. The function works as expected. 

I think that any such future further confusion can be avoided if issue #310 is incorporated into tomviz.
