### ISSUE TITLE
Add ability to set tilt angles for a tilt series

### ISSUE THREAD

**Issue by utkarshayachit** [OpenChemistry/tomviz#35]
* Show tilt angles on the Data Properties panel
* Edit tilt angles on Data Properties panel
* Add option to context menu/toolbar to mark a data set as a tilt series.
* Add checkbox to File | Open to open a file as tilt series.

**Comment by mathturtle** [comment]
@cryos @Hovden:
@utkarshayachit and I talked about this a bit last week.  The general idea is that we will add a metadata array to the dataset either as a field data array in VTK or by adding some 'annotation' mechanism to tomviz DataSource objects for metadata.  Then DataSources will be marked as either a volume or a tilt series and based on that other parts of the GUI will be activated/deactivated.

I do have a question for @Hovden:
What is the data format of a tilt angle?  Is it a single number, a set of euler angles, or some other rotation format?  Do we need to save an axis of rotation as well?

@cryos:
Do we want to try to keep everything in the vtk data object as field data or should we add a general annotation mechanism to the tomviz DataSource class?  For the purposes of saving state, it may be easier to do the second since the intermediate VTK objects are not saved and we'll have to record the tilt angles that have been added in the state file somehow.

**Comment by Hovden** [comment]
In its simplest form, it will be a vector of angles often equally spaced, but not always - e.g. [-70, -68, -66 ... +66, +68, +70]. In the most general form, which would apply to a rare set of experiments, the angles could be a vector containing any euler angles. The angles must be modifiable to the user.

Tilt axis is another issue.  In the short term, we can just assume the closest tilt axis is along the x-direction. We could also allow the user to specify the closest principle tilt axis, such as x, y, or z but I would suggest we default it to the x-axis.  However, in reality the tilt axis can be any euler angle that passes through any region of the sample. Typically, we keep the tilt axis fixed - say the x-axis passing through the center of the data - and we then rotate and shift the data such that its axis of rotation lies along the x-axis. This process of alignment is done manually and is very important to the reconstruction. It a big missing part to the reconstruction process in tomviz.

**Comment by mathturtle** [comment]
Ok, I talked to @utkarshayachit earlier.  For a first pass we are only going to support the single vector of angles.  And @cryos you can ignore the earlier question, @utkarshayachit likes the idea of using the vtkFieldData.

**Comment by mathturtle** [comment]
I have a PR to support some of this up ( #122  ).

**Comment by mathturtle** [comment]
The branch that supports some/most of this issue has been merged.  However, there is not much that can be done with data that has tilt angles yet.

**Comment by Hovden** [comment]
The tilt angles should not be visible in the data properties menu unless the dataset has been marked as a tilt series.

We also will need to have a get_tiltangles() routine callable from python. Given the time constraints, I think that the python part is low priority for this release.

**Comment by mathturtle** [comment]
I'll see what I can do about hiding the tilt angles in the data properties panel.

I'll take a look at the python thing too, I don't think it should be too hard.

**Comment by mathturtle** [comment]
I've got the python part working too, but in a separate PR so we can choose what makes it into 0.6.

**Comment by Hovden** [comment]
Definitely merge into this release if we can. Not having tilt angle metadata has been a big technicality on our claim for proof of concept reconstruction within tomviz. This is an important first step. Thanks.

**Comment by Hovden** [comment]
When I mark a volume data set as a tilt series, I lose the ability to run the data transforms. They become grayed out for selection on the "Data Transforms" menu. All of the data transforms should be able to run on either data type.

**Comment by mathturtle** [comment]
Oh.  We thought that there would be separate data transforms for tilt series data.  But that's a simple fix, I can remove the code that disables them for tilt series.

**Comment by Hovden** [comment]
Looks good; works properly for this release. Might want to polish up the UX in future issue requests.
