### ISSUE TITLE
Suggested screen shot features

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#377]
using: tomviz 0.7.2-122-g6c7ae98

I have a couple of usability suggestions for the Save screenshot feature:

1) Allow for a transparent background. This makes really nice figures for presentations, or allows you to change the background later for a paper figure. It could be an option in the Override color palette drop down box.

2) The Lock Aspect option (little red button on the right of the resolution boxes)  should be turned on by default.

**Comment by mathturtle** [comment]
1) I think this is a really good idea.  I don't know how difficult it will be to implement though.  It may already be in ParaView.

2) I think this is much more user-dependent.  Lock Aspect locks the aspect ratio of the output image to your VTK view's current aspect ratio which can be really strange.  Depending on the user and how their panels are laid out, they may or may not want this on.  When I have used this in ParaView I always specify both output image dimensions rather than using Lock Aspect.

**Comment by ercius** [comment]
I think 1 will be very useful.
Maybe I am expecting different behavior from the screen shot function. I want to capture exactly what is in the VTK viewer just at higher resolution than my screen resolution. Ill try it your way and see how it works.

**Comment by ercius** [comment]
Bump.

Any chance we can get this impemented? It will help with journal figure and presentation preparation.

**Comment by Hovden** [comment]
@ercius
As a temporary solution you can use a white background for figures

**Comment by mathturtle** [comment]
So I just did some digging into the code that creates screenshots and it turns out there is a way to do 1.  ParaView has this same feature in progress.  I can put in a hack that will enable this feature in tomviz now and remove it when ParaView has this option in its save screenshot dialog.  I don't see any pressing bugs so I'll work on this this afternoon.

Notes to self: ParaView saves the value of vtkSMViewProxy::TransparentBackground in settings.

**Comment by Hovden** [comment]
Transparent feature works great! These little things can go a long way when preparing figures for manuscripts.

I'm going to close this issue. @ercius feel free to open up the lock aspect option as a new issue.

<img width="900" alt="screen shot 2016-08-25 at 10 42 20 am" src="https://cloud.githubusercontent.com/assets/6197997/17973499/b6804a30-6ab0-11e6-8f96-beadc319a11f.png">
