### ISSUE TITLE
Global mapping data for data set not available

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#380]
I found a bug with respect to the "global" mapping data for a data set in 0.7.2-122-g6c7ae98. Click on a data set name in the Viz Modules list. The mapping data graph in the Properties box is not shown. I also can not click on the Set Range button to set a global range for all subsequent visualization modules. See attached file for details.

Correct view (from 0.7.2):
![mappingdatacorrect](https://cloud.githubusercontent.com/assets/15657108/14925448/5a60554e-0dfc-11e6-83bc-4e06144c2447.jpg)

Incorrect view (from 0.7.2-122):
![mappingdatabug](https://cloud.githubusercontent.com/assets/15657108/14925449/5a60cb32-0dfc-11e6-941c-c701e6c4335a.jpg)

**Comment by cryos** [comment]
@cquammen any ideas on this?

**Comment by cquammen** [comment]
Will take a look this afternoon.

**Comment by cquammen** [comment]
Hmm, I am unable to reproduce locally. The color map editor is not even present when the "global" color map is in effect.

Against which version of ParaView did you build tomviz? Or is this a binary you downloaded?

**Comment by cryos** [comment]
He says in the report - release compared to 0.7.2-122, I am guessing this is from a nightly build. I was just looking at this. I have a build on Linux with 0.7.2-127 here, using ParaView master from this morning. I see the global mapping data - you have to click on the data set in order to see it show up. It seems to appear as expected here, and I can rescale the range by clicking on the rescale button.

It even shows a restricted range on the central histogram widget now. The color bar only shows the first color value for me now though, in the central widget. The ability to add colors seems to be broken in the central widget, and it only shows the last color fading out to white. Not sure if something changed in ParaView as I tested this and it was working well.

**Comment by ercius** [comment]
I just tried this again today after rebooting my Windows 7 system. The mapping data is not available in the nightly version as I previously reported. I also can not click on the buttons to the right of the mapping data plot.

Im currently downloading the newest nightly and will check with that. It was likely related to other updates occurring during that time and fixed shortly after I downloaded the nightly (0.7.2-122-g6c7ae98) on 4/27/2016 at 2:21PM. Ill check back when I install the newest nightly.

**Comment by cryos** [comment]
It could be a Windows issue too, I can take a look on my Windows 7 test machine later today. I want to make sure we address these issues as we prepare to make our next release.

**Comment by cquammen** [comment]
Thanks for the clarification, Marcus. I just tried to reproduce the observed behavior observed by @ercius with version 0.7.2-122-g6c7ae98 on Windows 10 and could not.

I'm not exactly clear on what you are seeing, @cryos. I can rescale to a range entirely inside the range [0, 255] and the color bar and opacity function appear reasonable. I can edit any of the colors by double-clicking on their control points.

However, if I rescale to a range like [0, 3000], the axis is left at [0, 255] and I see only the control points that fall in the range [0, 255]. Perhaps the axis x-range should be updated to the custom data range?

**Comment by ercius** [comment]
Im on Windows 7 machine with a Nvidia GeForce GTX 280. I downloaded the nightly to another computer running Windows 10 with a Geforce Nvidia card (had never run tomviz before) and see the same exact issue. I also tried loading the sample data set and see the same issue. I can screen share or upload a video of this in action if you cant reproduce it.

To reproduce the issue:
1) Load a fresh instance of tomviz 0.7.2-122
2) Load the sample data set with default options
3) Click on the data set name in the Pipe lines --> Visualization Modules tab (Recon_NanoParticle_doi_10.1021-nl103400a.tif)
4) In the Properties tab, nothing is clickable in the Mapping data section and the Mapping data (see previous screen shot) is not visible.

I tried to download a more recent nightly from the tomviz website, but I still only get 0.7.2-122-g6c7ae98. I cant test with a newer binary until I can get a new nightly.

**Comment by mathturtle** [comment]
Yeah, the binaries for Windows are lagging a bit.  We share the machine with some other projects and we are queued behind a bunch of SMTK builds right now.

**Comment by cquammen** [comment]
@ercius Any chance we can get the TIFF image you are loading?

**Comment by cryos** [comment]
@cquammen the sample data set is bundled with the binaries offered for download, and available from the menu. You can see the URL in the superbuild somewhere - it is pretty small.

**Comment by cryos** [comment]
The issues I mentioned have gone away after a reboot/rebuild, may have been an inconsistent build. I was able to reproduce the issue with the missing transfer function editor on Linux now though - built master (0.7.2-136), with the latest ParaView (13c765a), and loading the MEDIUM or SMALL data set, clicking on the data item in the visualization modules, the mapping data is showing as blank for me consistently.

**Comment by mathturtle** [comment]
I tried with a fresh build of ParaView and tomviz master branches and still couldn't reproduce (I'm on Ubuntu 15.10).

**Comment by cquammen** [comment]
Hmm, this is frustrating. I cannot reproduce with the same versions of tomviz and ParaView as @cryos on Mac OS X.

I ***have*** noticed some repainting problems in ParaView built against Qt 5. If you scroll the Color Map Editor, the transfer function editor widgets do not repaint as expected. They stay in place with some artifacts or go black while the surround UI moves with the scroll action. Mousing over the transfer function editor finally forces a repaint. Since this is the widget tomviz uses, I suspect the two issues may be related. This is all observed in ParaView 5.0.1-413-g13c765a built against Qt 5.6.0.

**Comment by cryos** [comment]
I just merged #397, which helps on Linux but I want to see if it does the same on other platforms. If nothing else this is a better pattern where we avoid processing/initialization until the point at which it will be shown on the screen. I was unable to reproduce this bug on Linux with this patch, but could repeatedly do so before.

**Comment by ercius** [comment]
@cryos I missed your comment that this patch was applied. I just downloaded 0.7.2-145 and this seems fixed on Windows 10 (I recently updated). Thanks for addressing this!

**Comment by cryos** [comment]
Thanks for confirming, this is in the 0.8.0 release we just tagged.
