### ISSUE TITLE
Setting global mapping data range makes state file saving/loading unstable

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#381]
tomviz version: 0.7.2 (release)
OS: Windows 7

1) Click on the data file name in the Viz Modules.
2) In the properties box click on the Set range button located to the right of the Mapping data (second from the top, looks like a C) and enter any values in the popup box
![mappingdatacorrect](https://cloud.githubusercontent.com/assets/15657108/14925583/03de6bb0-0dfd-11e6-86c5-0e6070085111.jpg)
3) Save a state file
4) load the state file
5) Error is produced and tomviz becomes unstable. Sometimes it just crashes hard.
![error](https://cloud.githubusercontent.com/assets/15657108/14925668/5e1dd412-0dfd-11e6-8189-604b314e5399.jpg)

Loading old state files created with 0.7.2 using this feature also do not work with the daily tomviz version (0.7.2-122) probably connected to issue #380 .

**Comment by cryos** [comment]
@mathturtle can you look into this issue please.

**Comment by mathturtle** [comment]
I've tried a few things and I'm not seeing the instability/crash right now.  I even checked out that commit and didn't see this.  I didn't see anything in valgrind either.  I know that #378 has been fixed since this commit, so maybe that was causing this.  Or one of the bugs I fixed while working on my progress bar branch... I don't know.

@ercius Can you give me more details?  Do you have any transforms applied to the data or any extra modules visible?  If possible can you send me a state file that causes this to happen?

**Comment by ercius** [comment]
I'll check this tomorrow. I also had issues with the crop transform but I
used a fresh Tomviz state to produce this issue.

**Comment by ercius** [comment]
@mathturtle Looks like this was an issue with my own system. I rebooted it last night to install updates and now all of the state files I had trouble with load fine. Sorry for the confusion.

**Comment by mathturtle** [comment]
Ok.  Glad it's fixed now.

**Comment by cryos** [comment]
Thanks for following up on this @ercius
