### ISSUE TITLE
Instruction for installing ITK

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#402]
The build version of tomviz now requires ITK. Can we update the instruction page (https://github.com/OpenChemistry/tomviz/blob/master/BUILDING.md) to show how to install ITK properly?

**Comment by mathturtle** [comment]
In my experience, you have to either build ITK yourself, or change the compiled in RPATHs on Linux/OSX to get this to work.  The superbuild works by replacing these paths, which you can do locally (it is complicated though).  Otherwise you really need to compile it yourself.  Do you want instructions (or possibly a script) to build ITK or instructions for fixing up the ITK that the superbuild uses?

**Comment by Hovden** [comment]
I suggest building ITK instructions / script if it is less complicated and avoids ad-hoc solutions.

**Comment by cryos** [comment]
Let's just document the ITK build steps, same as we do for ParaView.
