### ISSUE TITLE
Save State / Save Data menu on OSX

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#408]
It would be better if the Save State / Save Data matched the "Open" data menu layout. Is this easy?

Open data looks like this:
<img width="706" alt="screen shot 2016-05-23 at 2 21 01 pm" src="https://cloud.githubusercontent.com/assets/6197997/15480143/e6d32936-20f1-11e6-949d-6e1c85431161.png">

Save data looks like this:
<img width="683" alt="screen shot 2016-05-23 at 2 21 31 pm" src="https://cloud.githubusercontent.com/assets/6197997/15480147/ee3d665a-20f1-11e6-9bb0-299dff54afbc.png">

**Comment by mathturtle** [comment]
> Is this easy?

Not really.  The open data menu is using ParaView's custom UI that which shows all available readers.  I just limit the available readers via a whitelist in the proxy definition manager.

Save Data could use this infrastructure if you are OK with selecting from all the ParaView writers... I guess I could add a whitelist here too, so this isn't *that* hard.  Right now it uses a default QFileDialog rather than ParaView's save data dialog.

Save State uses a default QFileDialog as well, but there isn't really an easy way to make it use ParaView's custom dialog that I know of.

**Comment by Hovden** [comment]
Ok, good to know. Let's leave it for another time. It is low-priority.

**Comment by cryos** [comment]
This was resolved, there are still one or two ParaView open/save file dialogs lingering, but we did replace a number of them to offer better consistency.
