### ISSUE TITLE
UI Crashes when clicking between visualization modules.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#414]
Crashes when clicking between visualization modules (OSX):
1) open two datasets, such as sample data reconstruction.
2) click quickly between visualization modules and datasets in the pipeline

**Comment by mathturtle** [comment]
This doesn't appear to have anything to do with the visualization modules... It is clicking on the dataset that is crashing tomviz for me.  This is another OSX + Qt5 issue (or so it appears).  When the data properties panel is loading, I get a lot of messages like this:
```
QWidget::repaint: Recursive repaint detected (:0, )
```
Each time I switch between the module properties panel being shown and the data properties panel being shown (especially if I'm selecting a dataset that is not the last one shown) I get a longer wait while it figures out the repaint.  Given that the trace in lldb is >25000 frames, I'm guessing this is a stack overflow.

**Comment by mathturtle** [comment]
So I actually managed to track this down a bit more today (Well, I found the DataPropertiesPanel was slow to load and did some debugging to find out why, then remembered this issue).  Anyway, the problem is in DataPropertiesPanel where we override paintEvent to call our update() method before repainting.  But update() modifies the UI, which then triggers another round of repaints and another paintEvent call.  @cryos said he was going to fix this as part of his branch to remove the colormap from the data properties panel.

**Comment by cryos** [comment]
Hopefully this is fixed, I didn't look at this particular issue directly, but I did rename the slot, made it a protected member, and removed the render slot that wasn't needed. I think update() was badly named, let me know if things look better the loop should hopefully be gone now.

**Comment by mathturtle** [comment]
I just tried and couldn't reproduce this bug.  It seems fixed to me.  @Hovden?

...I did find a new bug, but I'll create a new issue for that.

**Comment by mathturtle** [comment]
@Hovden ping?  Can we close this?

**Comment by Hovden** [comment]
Looks ok. Can't break it.
