### ISSUE TITLE
Autosave dialogue appears after minimization (OSX)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#515]
Minimize tomviz. Then open it back up. Autosave dialogue appears.

**Comment by cquammen** [comment]
Just tried it, didn't see an Autosave dialog. Is it the dialog that warns you that autosave files exist?

**Comment by mathturtle** [comment]
You have to wait 5 minutes for the first autosave file to be created... but I just reproduced this.  My guess is that I am using the wrong signal for when to show this.

**Comment by cquammen** [comment]
Ah, okay. I'll leave this to you, @mathturtle.

**Comment by Hovden** [comment]
When I "force quit" I am not prompted to load an autosave when restarting. I don't know how to crash it to test that it is working properly.

**Comment by mathturtle** [comment]
If you run the executable directly from the command line (run `tomviz.app\Contents\MacOS\tomviz`), then you can press Control-C in the terminal and it will kill it.  I think force quit may try a normal quit first before killing it.  Or you could try to find the equivalent of Task Manager's End Process button in the OSX Activity Monitor.  Remember you have to wait about 5 minutes to kill it so that there is an autosave file present.

**Comment by Hovden** [comment]
Looks good. It was fixed in the next build.
