### ISSUE TITLE
Center moved and reset button disabled

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#592]
tomviz 0.9.1, Windows 10
tomviz 0.9.1-101, WIndow 10

I see strange behavior with regards to the data center connected to the slice and orthoslice modules. Ive also seen this in previous builds but only just figured out how to reproduce it. Here is a set of instructions to create the issue.
1) Load the sample data reconstruction
2) Turn on Show Center. It is at the center of the data as expected
3) Click on the Slice module. The center is now at the edge and centered on the Slice
4) Notice that Reset Center button is grayed out
5) Click on Orthoslice module. Reset Center button is now enabled. The center is also now placed in the center of the data with the orthoslice.

There are other strange behaviors you can get with adding and deleting the Slice and Orthoslice modules with respect to the data center position and status of the Reset Center button. For example:
a) Place the center anywhere but the data center. Click on OrthoSlice or Slice modules and the center is set to the center of the generated slice.
or...
b) Load the example data set. Delete the automatically generated Orthoslice module. Notice that "Reset Center" is grayed out.

**Comment by ercius** [comment]
This still occurs in 0.9.3. Interestingly, it occurs when you add a slice (non-orthogonal) and the arrow end is outside the coordinate system. The coordinate system increases to include the arrow end and then the rotation center is offset from the center of the data. Its a slightly annoying usability issue, but nothing major.

**Comment by cquammen** [comment]
Developer's note: ParaView sets the enabled state of the "Reset Center" button based on whether a representation is active - when no representation is active, it is disabled, when a representation is active, it is enabled. ModuleSlice does not create a representation but instead adds a widget directly to the view's render window. As a result, when it is selected, no representation is active, and the "Reset Center" button is disabled.

**Comment by cryos** [comment]
Good to know, we should override that behavior as we don't want to be restricted to representations. Thanks for the extra information.

**Comment by psavery** [comment]
Hi Peter,

I'm looking at this bug now. However, I haven't been able to reproduce the change-of-center bugs on the latest Windows (or Ubuntu) version of Tomviz. My Windows version is Tomviz 1.3.1. Maybe the problem has been fixed? I am able to click on "slice", and the center axes do not move - even if I place the center axes somewhere else. If I click "orthogonal slice", the center axes increase in size, but the center does not move either. Indeed, left-clicking and dragging in the render window shows that it is still rotating around the displayed center axes as well.

If you get a chance, can you confirm that this no longer happens?

However, the graying out of the reset button still appears to be a bug. Anytime you perform a slice, the "Reset Center" button grays out (even if the center is somewhere other than the starting center). So that is still a bug.

Also, the slice arrow doesn't display its arrowheads (or the central ball) immediately until the slice properties are modified in some way.

**Comment by cryos** [comment]
This is now resolved.
