### ISSUE TITLE
ITK segmentation doesn't work on sample datasets

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#635]
I get this error when doing segmentation on sample datasets:

Exception encountered while running BinaryThreshold
"itkTemplate : No template [<class 'itkImagePython.itkImageD3'>] for the itk::PyBuffer class"

**Comment by cquammen** [comment]
Is this a local build or nightly binary?

**Comment by yijiang1** [comment]
My local build.

**Comment by cquammen** [comment]
The nightly binary downloaded yesterday appears to work fine and @cjh1 successfully tested the new Otsu thresholding transform on his local build, so I think this is a build issue.

Did you compile according to the directions posted at https://github.com/OpenChemistry/tomviz/blob/master/BUILDING.md? For convenience, I've reposted them here:

```
cd ..
git clone git://itk.org/ITK.git
cd ITK
git checkout v4.9.0
cd ..
mkdir itk-build
cd itk-build
cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
  -DITK_LEGACY_REMOVE:BOOL=ON \
  -DITK_LEGACY_SILENT:BOOL=ON \
  -DITK_USE_FFTWD:BOOL=ON \
  -DITK_USE_FFTWF:BOOL=ON \
  -DModule_BridgeNumPy:BOOL=ON \
  -DBUILD_TESTING:BOOL=OFF \
  -DITK_WRAP_PYTHON:BOOL=ON \
  -DBUILD_EXAMPLES:BOOL=OFF \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  ../ITK
cmake --build .
```

Note that I have only found ITK git tag v4.9.0 to work reliably.

**Comment by yijiang1** [comment]
Yes I built my ITK following the instruction above.
Sorry I just realize that my description is not clear enough. My segmentation actually works well on the data imported from files. It only fails on the data generated from the "Sample Data" menu.

**Comment by cquammen** [comment]
Ah, thanks, that's a big help 😸

On my system, I actually get a crash with all the data sets in the "Sample Data" menu. The crash is at `OperatorPython.cxx:111-112`.

```
this->Internals->InternalModule.TakeReference(
      PyImport_ImportModule("tomviz._internal"));
```

Interestingly, the sample tif files load work just fine. The main difference between the tif files and generated sample data is that the sample data has a `double` voxel type whereas the loaded data sets are `unsigned char` or `unsigned int`.

Thoughts, @cjh1 ?

**Comment by cjh1** [comment]
I am able to recreate this so will take a look.

**Comment by cjh1** [comment]
It seems its any python operator applied to a generated sample dataset.

**Comment by cjh1** [comment]
So I found an issue in PythonGeneratedDataSource, doesn't look like a new issue (was not introduced by the operator cancellation work). A [fix](https://github.com/OpenChemistry/tomviz/pull/638) for this resolves the crash on my system. However, its not clear to me how the two issue are linked. Please try out the fix, thanks.

**Comment by cquammen** [comment]
Okay, now that @cjh1 has solved my crash, I see @yijiang1 's originally reported bug.

This error is caused because images with voxel type `double` are not supported by the ITK build specified by our build instructions. The workaround is to run `Convert to Float` first, then Binary Threshold.

Longer term, we should do some combination of the following to handle this situation:

1. Enable wrapping of `double` voxel images in ITK, which will increase the binary size and increase the ITK compile time
2. Enable only transforms in the Data Transforms menu that can be applied to the selected data set. That's probably something we want at some point anyway, but it doesn't make it obvious that you would need to apply Convert to Float first.
3. Do some behind-the-scenes casting of unsupported types to supported types, e.g., double to float. We can do a lot here, but will have to be smart about reporting when there is likely loss of information due to casting. For the data ranges I have seen in the sample data, we may not have to worry about that too much.

What say you, @cryos ?

**Comment by cryos** [comment]
I prefer 3, and in general think the use of 64 bit double precision floats is not needed, and certainly won't be visible in any visualization we produce unless it goes through a number of operations that are sensitive to some small deviations on a large signal.
