### ISSUE TITLE
Tilt angles are not initialized to zero

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#716]
1. Load a dataset.
2. Click Tomography menu -> Mark Data As Tilt Series
3. In the "Set Tilt Angles" dialog, switch to "Set Individually" mode.
   <img width="676" alt="screen shot 2016-10-28 at 2 30 06 pm" src="https://cloud.githubusercontent.com/assets/13088588/19817789/1e42a716-9d1b-11e6-8c5f-e0ad443754d1.png">
4. Click OK.
5. Open the "Set Tilt Angles" dialog again from the pipeline. Switch to "Set Individually" mode, now the tilt angles are filled with random values.
   <img width="679" alt="screen shot 2016-10-28 at 2 30 18 pm" src="https://cloud.githubusercontent.com/assets/13088588/19817878/7d5c0db4-9d1b-11e6-94c3-2d0ba6b3b296.png">

**Comment by mathturtle** [comment]
It is much more sporadic for me but I can reproduce it.  Maybe one in three times i see random data.  I'm looking into why it happens now.

**Comment by mathturtle** [comment]
@cjh1  Can you take a look at this?  The image going into the `ImageFuture` in `DataSource::getCopyOfImagePriorTo(Operator*)` is fine, but the one that comes back out in `EditOperatorDialog::getCopyOfImagePriorToFinished(bool)` has garbage data in the tilt angles data array.... sometimes.

Since it is inconsistent for me, I suspect a threading issue.  But I can't find it.  Valgrind gives a lot of errors, mostly use of uninitialized value warnings in `QString::number` called from the `SetTiltAnglesOperator` to populate the table.

**Comment by cjh1** [comment]
Sure, I will take a look.

**Comment by cjh1** [comment]
@mathturtle @yijiang1 Any tips on recreating this issue? A particular data set? I have tried several times with Debug and RelWithDebugInfo and haven't seen it?

**Comment by mathturtle** [comment]
I just load a dataset and mark it as a tilt series (I'm not sure it matters, but I hit OK on the tab where you set the tilt angles individually rather than by parameters).  Then double-click on the operator in the pipeline to pull up the GUI again and switch back to the set tilt angles individually tab.  About 1 in 3 times I get garbage data displayed for at least some of the angles (usually 6-10 are garbage, but you have to scroll and check them all).  I haven't seen Yi's all the angles are garbage data error.

**Comment by yijiang1** [comment]
I get garbage data pretty much every time and nearly all of the angles are filled with non-zero values.
@ElliotPadgett can reproduce this bug as well. However his garbage values are more sparse.

**Comment by yijiang1** [comment]
#744 does not fix this bug

**Comment by cryos** [comment]
You used the word fix #bug number which GitHub takes to indicate it fixes the bug, and so it auto-closes it on merge. If you want to avoid that then just say issue #xxx and it won't close the referenced bug.

**Comment by yijiang1** [comment]
I see. Good to know.

**Comment by cryos** [comment]
In general we will never assume a pull request fixes a bug unless the commits/conversation state that it does, so saying anything doesn't fix a bug shouldn't be required. @cjh1 is investigating this issue, and will hopefully have more to say soon.
