### ISSUE TITLE
Create child datasets in python script

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#764]
Is it possible to have a utility function that creates child datasets in python script (.py)?

It seems that child datasets creation is currently done in json script. However, not all transforms (especially tomography reconstruction) can use json script.

**Comment by cquammen** [comment]
You'll likely still need to define the JSON for the Operator to let Tomviz know a child data set is expected. The missing piece is being able to specify that a custom UI is used.

**Comment by mathturtle** [comment]
So I'm going to use this issue to discuss what I was asked at the meeting... convert the reconstruction operators to create child datasets.  This means converting them to use JSON files.  @yijiang1 I'm curious why you don't think they can use JSON files.

I have a question about the weighted back projection operator.  Right now the output size is a parameter and defaults to the Y size of the input image.  @cquammen is there a way to set a default like this with the current JSON files or do we need to add something to the format?

**Comment by yijiang1** [comment]
> I'm curious why you don't think they can use JSON files.

Some reconstruction methods have very complicated UI like this
<img width="500" alt="screen shot 2017-01-13 at 4 49 15 pm" src="https://cloud.githubusercontent.com/assets/13088588/21946893/63f8a0d6-d9b0-11e6-9db7-28e4ba6f7a52.png">

I have no problem using JSON files if they can create this kind of UI.

**Comment by cquammen** [comment]
Two approaches:

1). Remove the custom UI and replace it with one generated in JSON. You couldn't reproduce the exact UI shown here with the JSON, but you could probably get close. The labels can contain long descriptive strings, but they currently show up just on the left-hand side while the widgets show up on the right side.

2). Add to the JSON description something that indicates a custom UI is to be used. The logic would need to be added to AddPythonTransformReaction.cxx. You'll also need to handle passing parameters from the UI to the script.

2 seems like the better option to me because there will be some custom UI's that will be too awkward to express in JSON.

**Comment by cquammen** [comment]
> I have a question about the weighted back projection operator. Right now the output size is a parameter and defaults to the Y size of the input image. @cquammen is there a way to set a default like this with the current JSON files or do we need to add something to the format?

No, there isn't anything to set defaults from the input data at the moment. It would be useful to have, though.

**Comment by cryos** [comment]
This is now working.
