### ISSUE TITLE
tomviz crashes when used remotely by windows remote desktop

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#927]
I have a computer I use for calculations running windows 10, and I normally access it by remote desktop. However, tomviz will not run when I am using remote desktop. It does run when I connect a monitor to the computer.

The program just does not start and there is no error message. Windows event viewer logs the program crash and I can provide information from there if necessary.

Has anyone else tried running tomviz on a remote machine using windows remote desktop?

**Comment by cryos** [comment]
I think we need to work on improving how gracefully Tomviz fails, but this is due to remote desktop not supporting modern OpenGL. You can set up VNC, and use that to remote to the machine and it should work as expected. I would like to make sure we report that the required OpenGL capabilities are not present, @utkarshayachit do you see the same behavior with ParaView here?

**Comment by ercius** [comment]
Thanks for the information. Ill try VNC. 

Ill leave this open until the Paraview question is answered.

**Comment by cquammen** [comment]
ParaView will not work with Remote Desktop with the OpenGL 2 backend because it relies on the Microsoft generic renderer, which provides only a generic software renderer supporting OpenGL 1.1. ParaView/Tomviz require OpenGL 3.2. Shaders have never worked with Remote Desktop, and everything in the OpenGL 2 backed uses shaders.

I should be able to verify that ParaView does not run over Remote Desktop tomorrow.

**Comment by cquammen** [comment]
I checked this morning and was stunned to learn that I *could* run ParaView 5.2.0 with the OpenGL 2 backend **and** Tomviz on my Windows 10 laptop when connecting from the Microsoft Remote Desktop client for Mac. Even volume rendering works!

The graphics driver reported in ParaView's About dialog box reported that it was using the Intel integrated graphics on that machine, which supports OpenGL 4.3.X.

It appears to be possible after all, and I stand humbly corrected.

**Comment by mathturtle** [comment]
@cquammen If I recall correctly from some experiments we did for the dashboards, they fixed it in Windows 10.  So if both sides are Windows 10 (or apparently Windows 10 compatible) it should work.  But you have an old remote desktop on either side, you can't do it.  I was going to check with Rob when he gets back next week since I couldn't remember the details.

**Comment by ercius** [comment]
I'm using Windows 10 on both sides. Maybe I have some setting (i.e. lower
graphics mode) wrong though.

**Comment by cryos** [comment]
It could also be limited by the OpenGL on either side, I suspect that Tomviz is still crashing when the required OpenGL version is not available (it does on my Windows 7 test machine using an older embedded Linux graphics card). We need to improve that, and at least inform you that the program is unlikely to be able to run correctly.

**Comment by cquammen** [comment]
To close the loop on this, we won't be able to make Tomviz work on every Windows 10 Remote Desktop connection. We can perhaps do smarter OpenGL version testing, and that issue is tracked in #745. That's probably about the best we can do.
