### ISSUE TITLE
crash when loading state file with cloned data

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#983]
1. Load a dataset
2. Do some transform.
3. Clone data and choose "transformed data only" option
4. Save state
5. Load state file. Crash

**Comment by cryos** [comment]
This is a general issue with any data that is not saved to disk, we will look into it and add some fixes. It also affects the new cache operator for the same reasons.

**Comment by Hovden** [comment]
We should either prevent the user from saving state without first saving the cloned data
or warn the user that the data will not be saved into the state file (and prevent a crash).

**Comment by cryos** [comment]
Yes, @cjh1 is working on this, and I think at a minimum we can warn and skip problematic nodes in the graph so that we end up with a valid state file.

**Comment by cryos** [comment]
We just merged #1098 which does as discussed. New binaries should be available within an hour to test, there are some unexpected issues with saving cloned/child data that we are looking into. I think this issue is now resolved, but the larger issue of saving/restoring child data in the pipeline may require some larger changes.

**Comment by cryos** [comment]
I am going to mark this as resolved now, there are other issues tracking the need to ensure child/clone/snapshot data can be saved correctly.
